SELECT
    ID,
    DDATE,
    CAST(CAST(REG_NUM as varchar(24) character set win1251) as varchar(24) character set utf8) AS REG_NUM,
    CAST(CAST(ZAKON_NUM as varchar(24) character set win1251) as varchar(24) character set utf8) AS ZAKON_NUM,
    REG_DATE,
    CAST(CAST(DESCR as varchar(1024) character set win1251) as varchar(1024) character set utf8) AS DESCR,
    CAST(CAST(ZAK_OSNOVA as varchar(1024) character set win1251) as varchar(1024) character set utf8) AS ZAK_OSNOVA,
    DKIND_ID,
    SUBJECT_ID,
    DOKLADCHIK_ID,
    OTVETSTV_KOMITET_ID,
    OTVETSTV_PERSON_ID,
    POVEST_DATE,
    CONTROL_DATE,
    DATE_DEPUTAT,
    DATE_PREZ,
    DATE_GU,
    DATE_PROKUROR,
    DATE_PU_Z,
    DATE_PU_P,
    DATE_PU_P2,
    DATE_PU_2CH,
    DATE_PU_T,
    CAST(CAST(DATE_DEPUTAT_PRIM as varchar(255) character set win1251) as varchar(255) character set utf8) AS DATE_DEPUTAT_PRIM,
    CAST(CAST(DATE_PREZ_PRIM as varchar(255) character set win1251) as varchar(255) character set utf8) AS DATE_PREZ_PRIM,
    CAST(CAST(DATE_GU_PRIM as varchar(255) character set win1251) as varchar(255) character set utf8) AS DATE_GU_PRIM,
    CAST(CAST(DATE_PROKUROR_PRIM as varchar(255) character set win1251) as varchar(255) character set utf8) AS DATE_PROKUROR_PRIM,
    CAST(CAST(DATE_PU_Z_PRIM as varchar(255) character set win1251) as varchar(255) character set utf8) AS DATE_PU_Z_PRIM,
    CAST(CAST(DATE_PU_P_PRIM as varchar(255) character set win1251) as varchar(255) character set utf8) AS DATE_PU_P_PRIM,
    CAST(CAST(DATE_PU_P2_PRIM as varchar(255) character set win1251) as varchar(255) character set utf8) AS DATE_PU_P2_PRIM,
    CAST(CAST(DATE_PU_2CH_PRIM as varchar(255) character set win1251) as varchar(255) character set utf8) AS DATE_PU_2CH_PRIM,
    CAST(CAST(DATE_PU_T_PRIM as varchar(255) character set win1251) as varchar(255) character set utf8) AS DATE_PU_T_PRIM,
    CAST(CAST(STATUS as varchar(50) character set win1251) as varchar(50) character set utf8) AS STATUS,
    PREZIDENT_PODPIS_DATE,
    CAST(CAST(RKK_READY as varchar(3) character set win1251) as varchar(3) character set utf8) AS RKK_READY,
    CAST(CAST(SESSIA_NUM as varchar(24) character set win1251) as varchar(24) character set utf8) AS SESSIA_NUM,
    SESSIA_DATE,
    COLOR,
    CAST(CAST(NPP as varchar(24) character set win1251) as varchar(24) character set utf8) AS NPP,
    CAST(CAST(PRIM as varchar(1024) character set win1251) as varchar(1024) character set utf8) AS PRIM,
    EDIT_DATE,
    CAST(CAST(EDITOR_LOGIN as varchar(24) character set win1251) as varchar(24) character set utf8) AS EDITOR_LOGIN,
    CAST(CAST(FLAG_DELETED as varchar(1) character set win1251) as varchar(1) character set utf8) AS FLAG_DELETED,
    CAST(CAST(FLAG_DOWNLOADED as varchar(1) character set win1251) as varchar(1) character set utf8) AS FLAG_DOWNLOADED,
    TIMESTAMP_DOWNLOADED,
    OPUBLIK_DATE
FROM
    DOCUMS
WHERE ID BETWEEN :start AND :end

