create table if not exists DOCUMS
(
    ID                    INTEGER not null
        constraint PK_DOCUMS
            primary key,
    DDATE                 DATE,
    REG_NUM               VARCHAR(24),
    ZAKON_NUM             VARCHAR(24),
    REG_DATE              DATE,
    DESCR                 VARCHAR(1024),
    ZAK_OSNOVA            VARCHAR(1024),
    DKIND_ID              INTEGER not null,
    SUBJECT_ID            INTEGER,
    DOKLADCHIK_ID         INTEGER,
    OTVETSTV_KOMITET_ID   INTEGER,
    OTVETSTV_PERSON_ID    INTEGER,
    POVEST_DATE           DATE,
    CONTROL_DATE          DATE,
    DATE_DEPUTAT          DATE,
    DATE_PREZ             DATE,
    DATE_GU               DATE,
    DATE_PROKUROR         DATE,
    DATE_PU_Z             DATE,
    DATE_PU_P             DATE,
    DATE_PU_P2            DATE,
    DATE_PU_2CH           DATE,
    DATE_PU_T             DATE,
    DATE_DEPUTAT_PRIM     VARCHAR(255),
    DATE_PREZ_PRIM        VARCHAR(255),
    DATE_GU_PRIM          VARCHAR(255),
    DATE_PROKUROR_PRIM    VARCHAR(255),
    DATE_PU_Z_PRIM        VARCHAR(255),
    DATE_PU_P_PRIM        VARCHAR(255),
    DATE_PU_P2_PRIM       VARCHAR(255),
    DATE_PU_2CH_PRIM      VARCHAR(255),
    DATE_PU_T_PRIM        VARCHAR(255),
    STATUS                VARCHAR(50) default 'В работе',
    PREZIDENT_PODPIS_DATE DATE,
    RKK_READY             CHAR(3),
    SESSIA_NUM            VARCHAR(24),
    SESSIA_DATE           DATE,
    COLOR                 TEXT,
    NPP                   VARCHAR(2),
    PRIM                  VARCHAR(1024),
    EDIT_DATE             TIMESTAMP(19),
    EDITOR_LOGIN          VARCHAR(24),
    FLAG_DELETED          CHAR(1)     default 'F',
    FLAG_DOWNLOADED       CHAR(1)     default 'F',
    TIMESTAMP_DOWNLOADED  TIMESTAMP(19),
    OPUBLIK_DATE          DATE
);
